### ISSUE TITLE
Not working with Contact Forms 7

### ISSUE THREAD

**Issue by captaincourageous** [hCaptcha/hcaptcha-wordpress-plugin#98]
I know this has been brought up before but hcaptcha does not work with Contact Forms 7.  All of my settings with hcaptcha.com are correct.

I do the following:
1. fill out form.
2. tap "I am Human" in hcaptcha
3. complete captcha
4. captcha validates
5. hit SEND
6. error message: "The Captcha is invalid."

**Comment by e271828-** [comment]
@kagg-design can you take a look?

**Comment by kagg-design** [comment]
This is fixed in the last version of the plugin.

**Comment by captaincourageous** [comment]
I turned it back on and encountered these issues:
1. hcaptcha does not display at all. all settings are as they were. contact forms 7 is enabled from the list. 
2. adding [hcaptcha] to the form itself in the form editor causes two instances of htcaptcha to be displayed - one on top of the other
3. filling out both: one seems to be ok but the other continuously invalidates. 

So... I deleted the plugin from my site and reinstalled direct from the "add new" page. Settings remained as i'd left them - deleting the plugin did not delete associated table data.

Issue remained as described above. :\

**Comment by kagg-design** [comment]
@captaincourageous It is my bug in 1.10.1, apologies. I have fixed it in 1.10.2. Will be published on wp.org soon.

**Comment by kagg-design** [comment]
We have published 1.10.2 on wp.org.

**Comment by captaincourageous** [comment]
Thans for all your hard work on this. 
Unfortunately it still does not function. Am I the only one who experiences this? I created a new site key and, rather than using it on the contact form, used it on the basic wp login to see if there was some conflict with contact forms 7. Alas, the same error: "Error: The Captcha is invalid."

**Comment by jeenusjunanio** [comment]
same issue is happening for me https://technoid.ae/contact-us-now/. Also this plugin from master is deactivated in my website due to fatal error

**Comment by e271828-** [comment]
FYI @kagg-design

**Comment by kagg-design** [comment]
@jeenusjunanio I do not see any issue with your page now - hCaptcha works.

Concerning the fatal error from the master - did you run composer and yarn?
